### ISSUE TITLE
Improve the code to handle more objects

### ISSUE THREAD

**Issue by Fabio-Morais** [glhr/labelbox-generate-data#1]
The current code just support 1 object, I would suggest improving the code by handle more objects.
Maybe a loop to all objects and at the end merge all objects with the specific colour.

**Comment by glhr** [comment]
Good point! I'll get to it when I have the time, but feel free to submit a pull request if you fix this in the meantime.

**Comment by Fabio-Morais** [comment]
Ok, I will try to fix it, because I have the same issue with LabelBox.
